--Find total customers by countries
SELECT 
	country,
	COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_id) DESC

--Find total customers by gender
SELECT
	gender,
	COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_id) DESC

--Find total products by category
SELECT 
	category,
	COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_id) DESC

--What is the average costs in each category?
SELECT
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC

--What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY SUM(f.sales_amount) DESC

--Find total revenue generated by each customer
SELECT 
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY SUM(f.sales_amount) DESC

--What is the distribution of sold items across countries?
SELECT 
	c.country,
	SUM(f.quantity) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.country
ORDER BY total_revenue DESC
